### PR TITLE
Finalize v5.0: fix CONTEXT.selfBoxIndex

### LINKED ISSUE #603: Fix CONTEXT.selfBoxIndex
Now it always returns `-1`.
Caused by `eq` in http://github.com/ScorexFoundation/sigmastate-interpreter/blob/a598658d63ad822a99ef91ecc79da906ad779ffe/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L639-L639 
Switching to `==` fixes it.

To test add:
```
  property("CONTEXT.selfBoxIndex") {
    testEval("CONTEXT.selfBoxIndex == 0")
  }
```
to `TestingInterpreterSpecification.scala`.

### PR DESCRIPTION
**Pull request by aslesarenko**
Closes #603

### CODE REVIEW

File: sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala [hunk 1]
```diff
@@ -746,18 +747,16 @@ case class CostingDataContext(
...
   @inline override def minerPubKey = _minerPubKey
 
-
-  private def findSelfBoxIndex: Int = {
-    var i = 0
-    while (i < inputs.length) {
-      if (inputs(i) eq selfBox) return i
-      i += 1
+  override def selfBoxIndex: Int = {
+    if (VersionContext.current.isEvaluateErgoTreeUsingJIT) {
```
Comment (kushti) [inline sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala:751]: Again, as there are different versioning schemes used in 5.0 codebase (interpreter-based vs tree-based), please comment why tree based is used here

Comment (aslesarenko) [reply sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala]: changed to activation-based versioning

**Review by kushti — APPROVED** [review]
