### PR TITLE
Finalize v5.0: fix  XorOf operation

### LINKED ISSUE #640: Fix xorOf
>"A chain of XORs—a XOR b XOR c XOR d (and so on)—is true whenever an odd number of the inputs are true and is false whenever an even number of inputs are true."

https://en.wikipedia.org/wiki/Exclusive_or

Xor(0, 1, 0) => 1 
as (0 ^ 1) ^ 0 = 1

Xor(0, 1, 1)  => 0
as (0 ^ 1) ^ 1 = 0

Current implementation - http://github.com/ScorexFoundation/sigmastate-interpreter/blob/42e55cbfd093252b8005e4607970764dd6610cbe/sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala#L41-L41

### PR DESCRIPTION
**Pull request by aslesarenko**
Closes #640

### CODE REVIEW

File: sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala [hunk 1]
```diff
@@ -40,8 +42,21 @@ class TestSigmaDslBuilder extends SigmaDslBuilder {
 
   @NeverInline
   override def xorOf(conditions: Coll[Boolean]): Boolean = {
-    // This is buggy version used in v4.x interpreter (for ErgoTrees v0, v1)
-    conditions.toArray.distinct.length == 2
+    if (Versions.currentErgoTreeVersion >= JitActivationVersion) {
```
Comment (kushti) [inline sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala:45]: Maybe condition can be done for interpreter version? I see no big semantic problems about it. In case of ergo tree version used, we need for roadmap for compiler and tooling update, but I do not see Github issues or other efforts towards that. Also, documentation for developers needed on how xorOf improperly working tor trees v. 0/1. 

I suspect if xorOf used anywhere, unlikely current behavior is intended, thus it could be cleaner to fix interpreter for all the version just.

Comment (aslesarenko) [reply sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala]: Ok, this can be done with the following condition 
`VersionContext.current.activatedVersion >= JitActivationVersion`. 
So the new behavior will only take effect after activation.

Comment (aslesarenko) [reply sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala]: It cannot be done in v5.0-fix-xorOf branch, because test harness is not ready yet. 
So I did it in a separate related PR (see part 2) where the changes are very small.

**Review by kushti — APPROVED** [review]
