### PR TITLE
Finalize v5.0: fix Coll.flatMap

### LINKED ISSUE #744: Allow return `x` in `flatMap` (e.g. `flatMap { (x: ...) => x }`)
From discord https://discord.com/channels/668903786361651200/840313005064585246/902729968331685988 :
```
I currently have a 

Coll[Coll[(SigmaProp, Coll[Byte])]]

that I am simply trying to flatten into a 

Coll[(SigmaProp, Coll[Byte])]

I tried 

flatMap{ (x : Coll[(SigmaProp, Coll[Byte])]) => x }

 but am running into an error that says: 

Unsupported lambda in flatMap: allowed usage `xs.flatMap(x => x.property)
```

### PR DESCRIPTION
**Pull request by aslesarenko**
Closes #744

### CODE REVIEW

File: sigmastate/src/main/scala/sigmastate/types.scala [hunk 1]
```diff
@@ -1637,18 +1637,24 @@ object SCollection extends STypeCompanion with MethodByNameUnapply {
...
+  }
+
   /** Implements evaluation of Coll.flatMap method call ErgoTree node.
     * Called via reflection based on naming convention.
     * @see SMethod.evalMethod
     */
   def flatMap_eval[A, B](mc: MethodCall, xs: Coll[A], f: A => Coll[B])
                         (implicit E: ErgoTreeEvaluator): Coll[B] = {
-    checkValidFlatmap(mc)
+    if (!VersionContext.current.isErgoTreeVersionGreaterV1) {
```
Comment (kushti) [inline sigmastate/src/main/scala/sigmastate/types.scala:1655]: Why tree-based activation here ?

Comment (aslesarenko) [reply sigmastate/src/main/scala/sigmastate/types.scala]: fixed, switched to activation-based versioning

**Review by kushti — APPROVED** [review]
