### PR TITLE
SOption.map and filter implementation

### LINKED ISSUE #422: Serialization fails for Soption.map and SOption.filter
Currently ignored tests SOption.map and SOption.filter are failing due to serialization roundtrip, the error is following:

sigmastate.lang.Terms$Lambda cannot be cast to sigmastate.Values$Constant
java.lang.ClassCastException: sigmastate.lang.Terms$Lambda cannot be cast to sigmastate.Values$Constant
	at sigmastate.serialization.ConstantSerializer.serialize(ConstantSerializer.scala:12)
	at sigmastate.serialization.ValueSerializer$.serialize(ValueSerializer.scala:172)
	at sigmastate.utils.SigmaByteWriter.putValue(SigmaByteWriter.scala:58)
	at sigmastate.utils.SigmaByteWriter.$anonfun$putValues$1(SigmaByteWriter.scala:61)

### LINKED ISSUE #425: For Option type, .map and .filter do not work
In addition to #422 , "Option.map" and "Option.filter" tests in BasicOpsSpecification are failing with the following error:

key not found: T
java.util.NoSuchElementException: key not found: T
	at scala.collection.immutable.ListMap$Node.applyInternal(ListMap.scala:129)
	at scala.collection.immutable.ListMap$Node.apply(ListMap.scala:126)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.eT$lzycompute(CostsImpl.scala:1276)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.eT(CostsImpl.scala:1276)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.<init>(CostsImpl.scala:1278)
	at special.collection.impl.CostsDefs$CostedOption$.proxyCostedOption(CostsImpl.scala:1374)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1271)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1111)

### PR DESCRIPTION
**Pull request by greenhat**
Close #422 
Close #425 

- [x] rebase after #459 is merged

### CODE REVIEW

File: src/main/scala/sigmastate/eval/CostingRules.scala [hunk 1]
```diff
@@ -479,6 +479,17 @@ trait CostingRules extends SigmaLibrary { IR: RuntimeCosting =>
...
     def isDefined: RCosted[Boolean] = constantSizeProperyAccess(_.isDefined)
     def isEmpty: RCosted[Boolean] = constantSizeProperyAccess(_.isEmpty)
+
+    def map[B](_f: RCosted[T => B]): RCosted[WOption[B]] = {
+      val f = asCostedFunc[T,B](_f)
+      val calcF = f.sliceCalc
+      val costF = f.sliceCost
+      val sizeF = f.sliceSize
+      val v = obj.value.map(calcF)
+      val c = costF(Pair(obj.cost, asSizeOption(obj.size).sizeOpt.get))
```
Comment (aslesarenko) [inline src/main/scala/sigmastate/eval/CostingRules.scala]: @greenhat please extract common subexpressions like this `asSizeOption(obj.size).sizeOpt`. Otherwise they are executed twice, which is quite costly.

Comment (greenhat) [reply src/main/scala/sigmastate/eval/CostingRules.scala]: Thanks. Fixed.

File: src/test/scala/special/sigma/SigmaDslTest.scala [hunk 2]
```diff
@@ -426,4 +426,15 @@ class SigmaDslTest extends PropSpec
     }
 
   }
+
+  property("Option methods equivalence") {
+    val opt: Option[Long] = ctx.dataInputs(0).R0[Long]
+    val eq = EqualityChecker(opt)
+    eq({ (x: Option[Long]) => x.get })("{ (x: Option[Long]) => x.get }")
+// TODO   eq({ (x: Option[Long]) => x.isEmpty })("{ (x: Option[Long]) => x.isEmpty }")
```
Comment (aslesarenko) [inline src/test/scala/special/sigma/SigmaDslTest.scala]: @greenhat  Please give details about what has to be fixed for this TODO

Comment (greenhat) [reply src/test/scala/special/sigma/SigmaDslTest.scala]: Done. It's not implemented yet.

File: src/test/scala/special/sigma/SigmaDslTest.scala [hunk 3]
```diff
@@ -426,4 +426,16 @@ class SigmaDslTest extends PropSpec
...
+
+  property("Option methods equivalence") {
+    val opt: Option[Long] = ctx.dataInputs(0).R0[Long]
+    val eq = EqualityChecker(opt)
+    eq({ (x: Option[Long]) => x.get })("{ (x: Option[Long]) => x.get }")
+    // TODO implement Option.isEmpty
+    //  eq({ (x: Option[Long]) => x.isEmpty })("{ (x: Option[Long]) => x.isEmpty }")
+    eq({ (x: Option[Long]) => x.isDefined })("{ (x: Option[Long]) => x.isDefined }")
+    eq({ (x: Option[Long]) => x.getOrElse(1L) })("{ (x: Option[Long]) => x.getOrElse(1L) }")
+    eq({ (x: Option[Long]) => x.filter(_ == 1) })("{ (x: Option[Long]) => x.filter({ (v: Long) => v == 1 }) }")
```
Comment (aslesarenko) [inline src/test/scala/special/sigma/SigmaDslTest.scala]: @greenhat yes, we can write shorter code in Scala, but here the test should prove equivalence of Scala and ErgoScript. If the code is different, it actually doesn't prove such an equivalence.

File: src/test/scala/sigmastate/CostingSpecification.scala [hunk 4]
```diff
@@ -197,9 +197,21 @@ class CostingSpecification extends SigmaTestingData {
...
+    val opt = "SELF.R5[Int]"
+    val accessOpt = accessBox + accessRegister
+    cost(s"{ $opt.get > 0 }") shouldBe (accessOpt + selectField + GTConstCost)
+    cost(s"{ $opt.isDefined }") shouldBe (accessOpt + selectField)
+    cost(s"{ $opt.getOrElse(1) > 0 }") shouldBe (accessOpt + selectField + GTConstCost)
+    // TODO (45 != 48)  cost(s"{ $opt.filter({ (x: Int) => x > 0}).isDefined }") shouldBe
+    //      (accessOpt + OptionOp + lambdaCost + GTConstCost + selectField)
+    // TODO (45 != 48)  cost(s"{ $opt.filter({ (x: Int) => x > 0}).isDefined }") shouldBe
+    //      (accessOpt + OptionOp + lambdaCost + GTConstCost + selectField)
+  }
```
Comment (aslesarenko) [inline src/test/scala/sigmastate/CostingSpecification.scala]: @greenhat what about this tests?

File: src/test/scala/special/sigma/SigmaDslTest.scala (hunk 3 above)
Comment (greenhat) [reply src/test/scala/special/sigma/SigmaDslTest.scala]: Got it. Fixed.

File: src/test/scala/sigmastate/CostingSpecification.scala (hunk 4 above)
Comment (greenhat) [reply src/test/scala/sigmastate/CostingSpecification.scala]: Fixed in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/469/commits/fee52bab7c1205a3f51add12b7a65953dc8fe1b6
