### PR TITLE
Parser layer for missing operations (#324)

### LINKED ISSUE #324: Add missing operations
#### New operations in SigmaPredef
See [spec](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/v2.0/docs/LangSpec.md#PredefinedFunctions)

#### New methods for various objects
See [spec](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/v2.0/docs/LangSpec.md#DataTypes)

#### Unary operations (// Testnet2)
```scala
! : SBoolean => SBoolean  // logical Not 
- : SNumeric => SNumeric  // negation operation
~ : SNumeric => SNumeric  // bitwise inversion of all bits
```

#### Bitwise operations (// Testnet2)
```scala
^ : (SBoolean, SBoolean) => SBoolean // logical XOR  

| : (SNumeric, SNumeric) => SNumeric // bitwise OR for all numeric types 
& : (SNumeric, SNumeric) => SNumeric // bitwise AND for all numeric types 
^ : (SNumeric, SNumeric) => SNumeric // bitwise XOR for all numeric types 

/** Returns this value bit-shifted right by the specified number of bits, 
filling in the left bits with the same value as the left-most bit of this. */
>> : (SNumeric, SNumeric) => SNumeric 

/** Returns this value bit-shifted left by the specified number of bits, 
filling in the new right bits with zeroes. */
<< : (SNumeric, SNumeric) => SNumeric 

/** Returns this value bit-shifted right by the specified number of bits, 
filling in the new left bits with zeroes. */
>>> : (SNumeric, SNumeric) => SNumeric 

/** Returns this collection bit-shifted left by the specified number of bits, 
    filling in the new right bits with zeroes. The size of collection is preserved. */
<< : (Coll[Boolean], SInt) => Coll[Boolean]

/** Returns this collection bit-shifted right by the specified number of bits, 
filling in the left bits with the same value as the left-most bit of this. 
The size of collection is preserved.*/
>> : (Coll[Boolean], SInt) => Coll[Boolean]

/** Returns this collection bit-shifted right by the specified number of bits, 
filling in the new left bits with zeroes. The size of collection is preserved.*/
>>> : (Coll[Boolean], SInt) => Coll[Boolean]

```

#### Operation to be replaces/renamed
Existing `Exponentiate` operation use symbol `^` which should be used for bitwise XOR instead.
See method `SGroupElement.exp` above.

Using bitwise operations and zip it is possible to implement existing Xor for collections (symbol `|`)

```scala
def Xor[T](c1: Coll[T], c2: Coll[T]): Coll[T] = c1.zipWith(c2, { (x, y) => x ^ y })
```

**UPDATE(Denys, Feb 12)**:

Status of the new operations in SigmaPredef:
Implemented in parser:
- `xorOf`;
- `byteArrayToLong`;
- `substConstants`;
- `executeFromVar`;
- `outerJoin`;
Implemented up to the typer:
- `!`(logical Not);
- `-`(negation);
- `~` (bitwise inversion);
- `^` (logical XOR);
- `|` (bitwise OR for Numeric);
- `&` (bitwise AND for Numeric);
- `^` (bitwise XOR for Numeric);
- `<<`, `>>`, `>>>` (bit shifts for Numeric);
- `<<`, `>>`, `>>>` (shifts for Collection); #418 

Status of the new methods for various objects:

**Boolean**:
Not implemented:
- `toByte`.

**Numeric**:
Implemented up to the typer:
- `toBytes`;
- `toBits`;
Not implemented(need to express "same" type):
- `abs`;
- `compare`; 

**BigInt**:
Implemented up to the typer:
- all new methods;

**Context**:
Not implemented (blocked by #350, see comments);

**Header** and **PreHeader**:
Not implemented, need to move in underlying types from ergo;

**AvlTree**:
Not implemented;

**Box**:
Implemented up to the typer:
- `tokens`;

**GroupElement**:
Implemented all new methods up to the typer:
- `exp`;

**Option**:
Implemented all new methods up to the typer:
- `toColl`;
- `flatMap`;
- `map`, `filter` (costing failing, see ignored tests in SigmaCompilerTest and BasicOpsSpec);

**Coll**:
**Implemented all new methods up to the typer**.
The following new methods are implemented fully(tests in CollectionOpsSpec): 
- `indexOf`;
- `segmentLength`;
- `indexWhere`;
- `lastIndexWhere`;
- `zip`;
- `partition`;
- `patch`;
- `updated`;
- `updatedMany`;
The following new methods are failing in evaluation (see ignored tests in CollectionOpsSpec):
- `flatMap` (output array instantiation error);
- `indices` (method call itself ends up in the cost func graph);

### PR DESCRIPTION
**Pull request by greenhat**
#324 

- [x] shifts on collection as methods on collection of any type;

### CODE REVIEW

File: src/main/scala/sigmastate/lang/SigmaBuilder.scala [hunk 1]
```diff
@@ -187,6 +188,20 @@ trait SigmaBuilder {
...
+  def mkBitInversion[T <: SNumericType](input: Value[T]): Value[T]
+  def mkBitOr[T <: SNumericType](left: Value[T], right: Value[T]): Value[T]
+  def mkBitAnd[T <: SNumericType](left: Value[T], right: Value[T]): Value[T]
+  def mkBitXor[T <: SNumericType](left: Value[T], right: Value[T]): Value[T]
+  def mkBitShiftRight[T <: SNumericType](left: Value[T], right: Value[T]): Value[T]
+  def mkBitShiftLeft[T <: SNumericType](left: Value[T], right: Value[T]): Value[T]
+  def mkBitRotateLeft(left: Value[SCollection[SBoolean.type]],
+                      right: Value[SInt.type]): Value[SCollection[SBoolean.type]]
+  def mkBitRotateRight(left: Value[SCollection[SBoolean.type]],
+                      right: Value[SInt.type]): Value[SCollection[SBoolean.type]]
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/lang/SigmaBuilder.scala]: @greenhat please make more meaningful arg names, like (bits, shift)

File: src/main/scala/sigmastate/lang/SigmaParser.scala [hunk 2]
```diff
@@ -67,11 +70,13 @@ object SigmaParser extends Exprs with Types with Core {
     case "<"  => LT(l, r)
     case "-"  => builder.mkMinus(l.asValue[SLong.type], r.asValue[SLong.type])
     case "|"  => builder.mkXor(l.asValue[SByteArray], r.asValue[SByteArray])
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/lang/SigmaParser.scala]: @greenhat This symbol `|` if for bitwise OR on Numeric

File: src/main/scala/sigmastate/lang/SigmaBuilder.scala (hunk 1 above)
Comment (greenhat) [reply src/main/scala/sigmastate/lang/SigmaBuilder.scala]: Fixed in builder methods. IR nodes names remain the same due to `TwoArgumentsOperation` in the hierarchy.

File: src/main/scala/sigmastate/lang/SigmaParser.scala (hunk 2 above)
Comment (greenhat) [reply src/main/scala/sigmastate/lang/SigmaParser.scala]: Yes, but we currently use "|" in test scripts. It goes way beyond the parser layer. I thought it could be fixed closer to the finish.

File: src/main/scala/sigmastate/lang/SigmaBuilder.scala (hunk 1 above)
Comment (ergomorphic) [reply src/main/scala/sigmastate/lang/SigmaBuilder.scala]: @greenhat I don't see much value in having this classification of operations. Maybe I missed something?

File: src/main/scala/sigmastate/lang/SigmaParser.scala (hunk 2 above)
Comment (ergomorphic) [reply src/main/scala/sigmastate/lang/SigmaParser.scala]: @greenhat Let's ignore those tests for a while, but make parser level feature complete.

File: src/test/scala/sigmastate/lang/SigmaParserTest.scala [hunk 3]
```diff
@@ -531,18 +532,179 @@ class SigmaParserTest extends PropSpec with PropertyChecks with Matchers with La
...
+  }
+
+  property("bitwise inversion unary op ~") {
+    parse("~OUTPUTS.size") shouldBe BitInversion(Select(Ident("OUTPUTS"), "size").asIntValue)
+  }
+
+  property("HEADERS methods") {
+    parse("HEADERS") shouldBe Ident("HEADERS")
+    parse("HEADERS.version") shouldBe Select(Ident("HEADERS"), "version")
+    parse("HEADERS.parentId") shouldBe Select(Ident("HEADERS"), "parentId")
```
Comment (ergomorphic) [inline src/test/scala/sigmastate/lang/SigmaParserTest.scala]: @greenhat Well, parser doesn't check it, but `HEADERS` is of `Coll` type

File: src/test/scala/sigmastate/lang/SigmaParserTest.scala [hunk 4]
```diff
@@ -531,18 +532,179 @@ class SigmaParserTest extends PropSpec with PropertyChecks with Matchers with La
...
+      MethodCallLike(Apply(Ident("Coll"), Vector(TrueLeaf, FalseLeaf)), "<<", Vector(IntConstant(2)))
+  }
+
+  property("BitCollShiftRightZeroed: bit-shifted right(zeroed) for numeric types") {
+    parse("Coll(true, false) >>> 2") shouldBe
+      MethodCallLike(Apply(Ident("Coll"), Vector(TrueLeaf, FalseLeaf)), ">>>", Vector(IntConstant(2)))
+  }
+
+  property("rotateLeft op: shift bit collection left") {
+    parse("Coll(true, false) rotateLeft 2") shouldBe
```
Comment (ergomorphic) [inline src/test/scala/sigmastate/lang/SigmaParserTest.scala]: @greenhat this should be method `rotateLeft` ( and the same for right)

File: src/main/scala/sigmastate/lang/SigmaParser.scala (hunk 2 above)
Comment (greenhat) [reply src/main/scala/sigmastate/lang/SigmaParser.scala]: Done.

File: src/main/scala/sigmastate/lang/SigmaBuilder.scala (hunk 1 above)
Comment (ergomorphic) [reply src/main/scala/sigmastate/lang/SigmaBuilder.scala]: Well, to generalize serializers we can add method `def args: Seq[SValue]` and have even more generic implementation.

File: src/test/scala/sigmastate/lang/SigmaParserTest.scala (hunk 3 above)
Comment (greenhat) [reply src/test/scala/sigmastate/lang/SigmaParserTest.scala]: Thanks! Missed that one. Fixed.

File: src/main/scala/sigmastate/lang/SigmaBuilder.scala (hunk 1 above)
Comment (greenhat) [reply src/main/scala/sigmastate/lang/SigmaBuilder.scala]: Agreed. Fixed.

File: src/test/scala/sigmastate/lang/SigmaParserTest.scala (hunk 4 above)
Comment (greenhat) [reply src/test/scala/sigmastate/lang/SigmaParserTest.scala]: Missed that one. This makes so much more sense than binary operation. :) 
Fixed.
