### PR TITLE
Recognize non-const ProveDlog and ProveDHTuple

### LINKED ISSUE #373: Value incorrectly recognized as a constant breaks (de)serialization
Code to reproduce:
```
    import sigmastate.interpreter.CryptoConstants.dlogGroup
    val bob = new ErgoLikeTestProvingInterpreter
    val env = Map("gA" -> dlogGroup.generator, "yA" -> bob.dlogSecrets.head.publicImage.value)
    val script = compileWithCosting(env,
      """{
        |    val c1 = OUTPUTS(0).R4[GroupElement].get
        |    val c2 = OUTPUTS(0).R5[GroupElement].get
        |    proveDHTuple(gA, c1, yA, c2)
        |}""".stripMargin
    ).asBoolValue // script successfully compiles
    val box = ErgoBox(10, script, 100) // this line gives error
```

### PR DESCRIPTION
**Pull request by greenhat**
Close #373 
Ref #374

### CODE REVIEW

File: src/main/scala/sigmastate/eval/TreeBuilding.scala [hunk 1]
```diff
@@ -296,9 +296,20 @@ trait TreeBuilding extends RuntimeCosting { IR: Evaluation =>
...
+          case gc: Constant[SGroupElement.type]@unchecked => SigmaPropConstant(mkProveDlog(gc))
+          case _ => mkProveDlog(g.asGroupElement)
+        }
       case Def(ProveDHTEvidenceCtor(In(g), In(h), In(u), In(v))) =>
-        SigmaPropConstant(mkProveDiffieHellmanTuple(g.asGroupElement, h.asGroupElement, u.asGroupElement, v.asGroupElement))
+        (g, h, u, v) match {
+          case (gc: Constant[SGroupElement.type]@unchecked,
+          hc: Constant[SGroupElement.type]@unchecked,
+          uc: Constant[SGroupElement.type]@unchecked,
+          vc: Constant[SGroupElement.type]@unchecked) =>
```
Comment (aslesarenko) [inline src/main/scala/sigmastate/eval/TreeBuilding.scala]: What if one of the matched values is not Constant?

Comment (greenhat) [reply src/main/scala/sigmastate/eval/TreeBuilding.scala]: @aslesarenko `ProveDHTuple` will not be wrapped in `ConstantNode`. See `case _`.
