### PR TITLE
Fix: Extract collections from registers

### LINKED ISSUE #88: Extract collection from register
I can't find an example of collection extraction from a register, and expected way to do this like `ExtractRegisterAs[SCollection[Boolean]](Self, R4)(SCollection[Boolean])` does not work

### LINKED ISSUE #98: Replace SByteArray to SCollection[Byte]
Byte type is needed for this
relates to #87, #88

### PR DESCRIPTION
**Pull request by ergomorphic**
Resolves #88
Resolves #98

### CODE REVIEW

File: src/main/scala/sigmastate/trees.scala [hunk 1]
```diff
@@ -104,7 +109,7 @@ case class AND(input: Value[SCollection[SBoolean.type]])
 
   //todo: reduce such boilerplate around AND/OR, folders, map etc
   override def transformationReady: Boolean =
-    input.evaluated && input.items.forall(_.evaluated)
+    input.evaluated && input.fold(_.items.forall(_.evaluated), c => true)
```
Comment (kushti) [inline src/main/scala/sigmastate/trees.scala]: why are you reducing in transformationReady() ?

Comment (ergomorphic) [reply src/main/scala/sigmastate/trees.scala]: this is not reducing. This probably confusing function name. It actualy does pattern matching ConcreteColletion and CollectionConstant cases. Check the function.
I can rename it in the next PR.
