### PR TITLE
Malicious test suite for deserializer

### LINKED ISSUE #198: Malicious test suite for deserializer
The goal is to fool deserializer into doing something bad and check that it catches this and responds with a clear exception throwing.
The test scripts can be handcrafted bytes.

### PR DESCRIPTION
**Pull request by greenhat**
Close #198 

- [x] empty;
- [x] zeros;
- [x] collection of a crazy size;
- [x] max bytes size limit;
- [x] tuple of tuples crazy deep;
- [x] add range check assert to `getUInt`;
- [x] crazy deep nodes  (AND/OR, etc)
- [x] look into LibFuzzer Corpus;
- [x] use exceptions instead of assert;
- [x] invalid type code;
- [x] invalid op code;
- [x] glue nested call depth tracker to the reader;

### CODE REVIEW

File: src/test/scala/sigmastate/serialization/DeserializationResilience.scala [hunk 1]
```diff
@@ -12,6 +12,11 @@ class DeserializationResilience extends PropSpec
     an[ArrayIndexOutOfBoundsException] should be thrownBy ValueSerializer.deserialize(Array[Byte]())
   }
 
+  property("max size limit") {
+    val size = 1024 * 1024 * 10
```
Comment (greenhat) [inline src/test/scala/sigmastate/serialization/DeserializationResilience.scala]: @ergomorphic should we assume that it's being taken care of by tx max size limit and don't bother checking?

File: src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala [hunk 2]
```diff
@@ -84,4 +85,9 @@ class TypeSerializerSpecification extends SerializationSpecification {
     roundtrip(STuple(SLong, SLong, SByte, SBoolean, SInt),
       Array[Byte](TupleTypeCode, 5, SLong.typeCode, SLong.typeCode, SByte.typeCode, SBoolean.typeCode, SInt.typeCode))
   }
+
+  property("tuple of tuples crazy deep") {
```
Comment (greenhat) [inline src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala]: @ergomorphic it's throwing `StackOverflow` now. We should have some depth limit.

**Comment by greenhat** [comment]
@ergomorphic Do you have other ideas on what to feed into deserializer? I've looked into fuzzing but it might be an overkill.

File: src/test/scala/sigmastate/serialization/DeserializationResilience.scala (hunk 1 above)
Comment (ergomorphic) [reply src/test/scala/sigmastate/serialization/DeserializationResilience.scala]: @greenhat I think we should check everything we can.

File: src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala (hunk 2 above)
Comment (ergomorphic) [reply src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala]: yes, that is what I mean by malicious tests. It is better to have synthetic tests which deterministically reporduce specific cases, like very deep trees or invalid codes etc. 
They should cover all existing error throwing cases.

Comment (ergomorphic) [reply src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala]: @greenhat We need to have something similar to Corpus described here http://www.llvm.org/docs/LibFuzzer.html

Comment (greenhat) [reply src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala]: @ergomorphic I've successfully tested the proof-of-concept for coverage-guided fuzzying in scala (based on scoverage). I've started the project https://github.com/greenhat/scalafuzz-scalac-plugin and I plan to have a random mutations working this week.

File: src/main/scala/sigmastate/serialization/ValueSerializer.scala [hunk 3]
```diff
@@ -107,16 +109,28 @@ object ValueSerializer extends SigmaSerializerCompanion[Value[SType]] {
       getSerializer(opCode).asInstanceOf[ValueSerializer[v.type]].serializeBody(v, w)
   }
 
+  private val nestedValuesDepthPerReader = TrieMap[Int, Int]()
```
Comment (greenhat) [inline src/main/scala/sigmastate/serialization/ValueSerializer.scala]: @ergomorphic I found it super ugly, but the alternative (passing the depth through `parseBody`) seems even uglier. I'm open to any ideas. :)

File: src/main/scala/sigmastate/serialization/SigmaSerializer.scala [hunk 4]
```diff
@@ -72,6 +75,8 @@ trait SigmaSerializerCompanion[TFamily] {
   def getSerializer(opCode: Tag): SigmaSerializer[TFamily, _ <: TFamily]
 
   final def deserialize(bytes: Array[Byte], pos: Position): (TFamily, Consumed) = {
+    if (bytes.length > Serializer.MaxInputSize)
+      throw new InputSizeLimitExceeded(s"input size ${bytes.length} exceeds ${ Serializer.MaxInputSize}")
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/serialization/SigmaSerializer.scala]: @greenhat we still have this old-style methods? Let's get rid of them completely. Even if we need the methods like this, they should be wrappers and they shouldn't have any logic other than wrapping.

File: src/main/scala/sigmastate/serialization/ValueSerializer.scala (hunk 3 above)
Comment (ergomorphic) [reply src/main/scala/sigmastate/serialization/ValueSerializer.scala]: @greenhat We already passing Reader along the tree (i.e. along all recursive calls). This means we can add  `getLevel` `setLevel` methods in the Reader interface so that serializers can update the corresponding state field if they need it.

File: src/main/scala/sigmastate/utils/Helpers.scala [hunk 5]
```diff
@@ -53,6 +53,12 @@ object Helpers {
       case (Some(a1), Some(a2)) => deepHashCode(a1) == deepHashCode(a2)
       case _ => false
     }
+
+  /**
+    * Helper to construct a byte array from a bunch of bytes. The inputs are actually ints so that I
+    * can use hex notation and not get stupid errors about precision.
+  */
+  def bytesFromInts(bytesAsInts: Int*): Array[Byte] = bytesAsInts.map(_.toByte).toArray
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/utils/Helpers.scala]: @greenhat Maybe check overflow?

File: src/main/scala/sigmastate/serialization/ValueSerializer.scala (hunk 3 above)
Comment (greenhat) [reply src/main/scala/sigmastate/serialization/ValueSerializer.scala]: @ergomorphic I've ruled that out initially due to probable SRP violation, but it's least of all other evils. :) Thanks.

Comment (greenhat) [reply src/main/scala/sigmastate/serialization/ValueSerializer.scala]: @ergomorphic Done `get/setLevel`.

File: src/main/scala/sigmastate/utils/ByteReader.scala [hunk 6]
```diff
@@ -172,6 +172,10 @@ class ByteBufferReader(buf: ByteBuffer) extends ByteReader {
   @inline override def position_=(p: Int): Unit = buf.position(p)
 
   @inline override def remaining: Int = buf.remaining()
+
+  private val lvl: AtomicInteger = new AtomicInteger(0)
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/utils/ByteReader.scala]: @greenhat Our Reader/Writer implementations are not thread safe, we should probably mention this in ScalaDoc. Because of this making `level` safe doesn't make much sense IMO. 
I also cannot make up a practical case for two threads working with the same Reader instance.

File: src/main/scala/sigmastate/utils/Helpers.scala [hunk 7]
```diff
@@ -58,7 +58,12 @@ object Helpers {
     * Helper to construct a byte array from a bunch of bytes. The inputs are actually ints so that I
     * can use hex notation and not get stupid errors about precision.
   */
-  def bytesFromInts(bytesAsInts: Int*): Array[Byte] = bytesAsInts.map(_.toByte).toArray
+  def bytesFromInts(bytesAsInts: Int*): Array[Byte] =
+    bytesAsInts.map{ i =>
+      // values from unsigned byte range will be encoded as negative values which is expected here
+      assert(i >= Byte.MinValue && i <= 0xFF, s"$i is out of the signed/unsigned Byte range")
+      i.toByte
+    }.toArray
```
Comment (ergomorphic) [inline src/main/scala/sigmastate/utils/Helpers.scala]: @greenhat I'm suspect here we have boxing of all the bytes in a generic sequence. 
Please check this and avoid by using imperative loop. 
In any case this should be imperative loop, because `map` uses CanBuildFrom with growing intermediate buffers, which are not necessary here because we know the resuting length.

File: src/main/scala/sigmastate/utils/ByteReader.scala (hunk 6 above)
Comment (greenhat) [reply src/main/scala/sigmastate/utils/ByteReader.scala]: Agree. That was an overkill.

**Comment by greenhat** [comment]
@ergomorphic All done.
